name: Helper - Build and deploy environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      DB_CONNECTION_STRING:
        required: true

jobs:
  build-push-backend-api-image:
    name: "Build & push backend api"
    uses: ./.github/workflows/build-push-image.yml
    with:
      display-name: "Build & push backend api"
      environment: ${{ inputs.environment }}
      image-artifact-name: backend-api
      image-artifact-filename: backend-api
      build-target: backend-api
      image-identifier: monolith-backend-api
    secrets: inherit

  deploy-container-apps:
    name: "Deploy container apps"
    uses: ./.github/workflows/deploy-container-app.yml
    needs: [build-push-backend-api-image]
    with:
      display-name: "Deploy container apps"
      environment: ${{ inputs.environment }}
      backend-api-image-tag: ${{ needs.build-push-backend-api-image.outputs.image-tag }}
    secrets: inherit

  run-db-migrations:
    name: "Run DB migrations"
    uses: ./.github/workflows/run-db-migrations.yml
    needs: deploy-container-apps
    with:
      environment: ${{ inputs.environment }}
    secrets:
      CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
